name: scopely-challenge-infra
services:
  player-database:
    container_name: "player-database"
    env_file:
      - ./environments/.player-database.env
    healthcheck:
      test: pg_isready -d player-database -U admin
    ports:
      - "5432:5432"
    volumes:
      - ./player-database:/var/lib/postgresql/data

  api-gateway:
    container_name: "api-gateway"
    image: "api-gateway"
    env_file:
      - ./environments/.api-gateway.env
    build:
      context: ./../scopely-challenge/
      dockerfile: Dockerfile.api-gateway
      args:
        NODE_ALPINE_VERSION: ${NODE_ALPINE_VERSION:?err}
        PORT: ${API_GATEWAY_PORT:?err}

  player-service:
    container_name: "player-service"
    image: "player-service"
    env_file:
      - ./environments/.player-service.env
    build:
      context: ./../scopely-challenge/
      dockerfile: Dockerfile.player-service
      args:
        NODE_ALPINE_VERSION: ${NODE_ALPINE_VERSION:?err}
        PORT: ${PLAYER_SERVICE_PORT:?err}

  battle-database:
    container_name: "battle-database"
    env_file:
      - ./environments/.battle-database.env
    healthcheck:
      test: pg_isready -d battle-database -U admin
    ports:
      - "5433:5432"
    volumes:
      - ./battle-database:/var/lib/postgresql/data

  battle-service:
    container_name: "battle-service"
    image: "battle-service"
    env_file:
      - ./environments/.battle-service.env
    build:
      context: ./../scopely-challenge/
      dockerfile: Dockerfile.battle-service
      args:
        NODE_ALPINE_VERSION: ${NODE_ALPINE_VERSION:?err}
        PORT: ${BATTLE_SERVICE_PORT:?err}

  battle-worker-service:
    container_name: "battle-worker-service"
    image: "battle-worker-service"
    env_file:
      - ./environments/.battle-worker-service.env
    build:
      context: ./../scopely-challenge/
      dockerfile: Dockerfile.battle-worker-service
      args:
        NODE_ALPINE_VERSION: ${NODE_ALPINE_VERSION:?err}
        PORT: ${BATTLE_WORKER_SERVICE_PORT:?err}
  rabbitmq:
    container_name: "rabbitmq"
    env_file:
      - ./environments/.rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
