name: scopely-challenge-infra
services:
  player-database:
    image: "postgres:${POSTGRES_VERSION:?err}"
    volumes:
      - ./initialize-player-database.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2"
          memory: "2g"
        reservations:
          cpus: "1"
          memory: "1g"
    storage_opt:
      size: "4g"
  battle-database:
    image: "postgres:${POSTGRES_VERSION:?err}"
    volumes:
      - ./initialize-battle-database.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "2"
          memory: "2g"
        reservations:
          cpus: "1"
          memory: "1g"
    storage_opt:
      size: "4g"
  rabbitmq:
    image: "rabbitmq:${RABBITMQ_VERSION:?err}"
    container_name: "rabbitmq"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "1g"
        reservations:
          cpus: "1"
          memory: "512M"
    storage_opt:
      size: "2g"
